import type { ComponentType, SVGProps } from 'react'
import {
  BuildingLibraryIcon,
  CurrencyDollarIcon,
  WrenchScrewdriverIcon,
  ShieldCheckIcon,
  DevicePhoneMobileIcon,
  HeartIcon,
  AcademicCapIcon,
  TruckIcon,
  HomeModernIcon,
  BuildingOffice2Icon,
  ScaleIcon,
  BriefcaseIcon,
  BuildingStorefrontIcon,
  ArrowsRightLeftIcon,
  MagnifyingGlassIcon,
  DocumentMagnifyingGlassIcon,
  ShieldExclamationIcon,
  BanknotesIcon,
  CubeTransparentIcon,
  GlobeAltIcon,
  DocumentTextIcon,
  ChatBubbleLeftRightIcon,
  ChartBarIcon,
  UserGroupIcon,
  StarIcon,
  LightBulbIcon,
  EyeIcon,
  CheckCircleIcon,
  ClockIcon,
  MapPinIcon,
  Cog6ToothIcon,
  EnvelopeIcon,
  PhoneIcon,
} from '@heroicons/react/24/outline'

type IconType = ComponentType<SVGProps<SVGSVGElement>>

const ICON_MAP: Record<string, IconType> = {
  BuildingLibraryIcon,
  CurrencyDollarIcon,
  WrenchScrewdriverIcon,
  ShieldCheckIcon,
  DevicePhoneMobileIcon,
  HeartIcon,
  AcademicCapIcon,
  TruckIcon,
  HomeModernIcon,
  BuildingOffice2Icon,
  ScaleIcon,
  BriefcaseIcon,
  BuildingStorefrontIcon,
  ArrowsRightLeftIcon,
  MagnifyingGlassIcon,
  DocumentMagnifyingGlassIcon,
  ShieldExclamationIcon,
  BanknotesIcon,
  CubeTransparentIcon,
  GlobeAltIcon,
  DocumentTextIcon,
  ChatBubbleLeftRightIcon,
  ChartBarIcon,
  UserGroupIcon,
  StarIcon,
  LightBulbIcon,
  EyeIcon,
  CheckCircleIcon,
  ClockIcon,
  MapPinIcon,
  Cog6ToothIcon,
  EnvelopeIcon,
  PhoneIcon,
}

export function getIcon(name: string, fallback: IconType = UserGroupIcon): IconType {
  return ICON_MAP[name] ?? fallback
}
